name: Build Termux App

on:
  push:
    branches:
      # Запускаем сборку для нашей новой ветки
      - my-integration-branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v5
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Cache Gradle packages
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew

    - name: Build with Gradle
      # Эта команда теперь, после наших оптимизаций, будет очень быстрой
      run: ./gradlew :app:assembleDebug

    - name: Upload arm64-v8a APK
      uses: actions/upload-artifact@v4
      with:
        name: termux-arm64-debug.apk
        # --- ИСПРАВЛЕННЫЙ И БОЛЕЕ НАДЕЖНЫЙ ПУТЬ ---
        # Мы используем "шаблон" (wildcard) '*', чтобы найти любой .apk файл
        # в этой папке. Так как мы знаем, что он там будет только один,
        # это самый надежный способ.
        path: app/build/outputs/apk/debug/*.apk
