name: Build Termux App

on:
  push:
    branches:
      - master # Изменено с 'main' на 'master'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Cache Gradle packages
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew

    - name: Build with Gradle
      # Запускаем сборку debug-версии для архитектуры arm64-v8a
      run: ./gradlew assembleArm64-v8aDebug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: termux-arm64-debug.apk # Изменено имя артефакта
        # Указываем точный путь к нужному нам APK
        path: app/build/outputs/apk/arm64-v8a/debug/app-arm64-v8a-debug.apk
